version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=localpass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
